version: '2.4'

services:
  scrapers:
    image: scrapers-lametro
    container_name: scrapers-lametro
    build: .
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - scrapers-cache:/tmp/cache
    env_file: ".env"
    environment:
      # Populate the local Councilmatic database
      DATABASE_URL: postgresql://postgres:postgres@postgres:5432/lametro
      DJANGO_SETTINGS_MODULE: pupa.settings
      OCD_DIVISION_CSV: "/app/lametro/divisions.csv"
    command: pupa update lametro
    # Connect the scraper container to the app network
    networks:
      - app_net

volumes:
  scrapers-cache:

networks:
  # Define connection to the app's Docker network
  app_net:
    name: la-metro-councilmatic_default
    external: true
