version: '2.4'

services:
  scrapers:
    image: scrapers-lametro
    container_name: scrapers-lametro
    build: .
    stdin_open: true
    tty: true
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - .:/app
    env_file: ".env"
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/opencivicdata
      DJANGO_SETTINGS_MODULE: pupa.settings
      OCD_DIVISION_CSV: "/app/lametro/divisions.csv"
    command: pupa update lametro

  postgres:
    container_name: scrapers-lametro-postgres
    image: postgis/postgis:11-3.3
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_DB: opencivicdata
      POSTGRES_PASSWORD: postgres
    volumes:
      - scrapers-lametro-db-data:/var/lib/postgresql/data
    ports:
      - 32001:5432

volumes:
  scrapers-lametro-db-data:
