name: 🔄 Full Scrape

on:
  schedule:
    - cron: '15 4 * * 0-4,6'  # At 12:15a bills, Sunday-Thursday and Saturday
    - cron: '5 4 * * 0-4,6'   # At 12:05a events, Sunday-Thursday and Saturday

  workflow_dispatch:
    inputs:
      rpm:
        description: How many requests per minute?
        type: string
        default: '60'
    
jobs:
  scrape_bills:
    concurrency: 
      group: full_scrape_bills
    uses: ./.github/workflows/scrape.yml
    with:
      object_type: bills
      window: 0
      rpm: ${{ inputs.rpm || '60' }}
    secrets: inherit

  scrape_events:
    needs: scrape_bills
    concurrency: 
      group: full_scrape_events
    uses: ./.github/workflows/scrape.yml
    with:
      object_type: events
      window: 0
      rpm: ${{ inputs.rpm || '60' }}
    secrets: inherit

  keepalive:
    if: github.event_name == 'schedule'
    runs-on: ubuntu-latest
    permissions:
      actions: write
    steps:
      - uses: liskin/gh-workflow-keepalive@v1